spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_v6?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&nullCatalogMeansCurrent=true
    username : root
    password : 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    #启用作业执行器
    async-executor-activate: false
    #启用异步执行器
    job-executor-activate: false
    #  databaseSchemaUpdate属性的取值：
    #  flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。#
    #  true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。#
    #  create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。#
    #  drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。
    #  database-schema-update: true
    database-schema-update: false
#    database-schema-update: drop-create
    history-level: full
    db-history-used: true
